targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          singleton: true
          lazy: true
          factory: false
          class_name_pattern: "DataSource$|DataSourceImpl$|Repository$|RepositoryImpl$|Service$|ServiceImpl$"
          

