// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgG1qAGnaLGrDjKcmlXZN46hzQuZmOqDc',
    appId: '1:363582784532:web:2a48702d835d34057fd301',
    messagingSenderId: '363582784532',
    projectId: 'chatapp-a1668',
    authDomain: 'chatapp-a1668.firebaseapp.com',
    storageBucket: 'chatapp-a1668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalFdGrSNO5JMrzMjBSw_FcxIYeZXJHow',
    appId: '1:363582784532:android:4b9121f0130a0a737fd301',
    messagingSenderId: '363582784532',
    projectId: 'chatapp-a1668',
    storageBucket: 'chatapp-a1668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvOkuCW90qw_9SzY1ke3lPDusxztf0s8',
    appId: '1:363582784532:ios:f3f4795543bb66ea7fd301',
    messagingSenderId: '363582784532',
    projectId: 'chatapp-a1668',
    storageBucket: 'chatapp-a1668.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvOkuCW90qw_9SzY1ke3lPDusxztf0s8',
    appId: '1:363582784532:ios:f3f4795543bb66ea7fd301',
    messagingSenderId: '363582784532',
    projectId: 'chatapp-a1668',
    storageBucket: 'chatapp-a1668.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgG1qAGnaLGrDjKcmlXZN46hzQuZmOqDc',
    appId: '1:363582784532:web:24e27a98c3164bd17fd301',
    messagingSenderId: '363582784532',
    projectId: 'chatapp-a1668',
    authDomain: 'chatapp-a1668.firebaseapp.com',
    storageBucket: 'chatapp-a1668.appspot.com',
  );
}
